### PR TITLE
Add more domains which auto-renewed on registrar side.

### PR DESCRIPTION
**Pull request by RayeN**
In scope of https://github.com/yola/production/issues/3002

### CODE REVIEW

**Comment by adrianmoisey** [comment]
Does this count as a bug fix, or functionality? (ie should it be `1.1.0` or `1.0.1`?)

**Comment by adrianmoisey** [comment]
:+1:

**Comment by RayeN** [comment]
Dunno actually, I would say - bugfix.

**Comment by RayeN** [comment]
Since we missed to add them initially :)

**Pull request merged**
